# @package _global_
defaults:
  - /base_configs/maxVQ_dmc
  - /oracles/dmc/cheetah_run
  - _self_
method_name: "MaxVQ"

seed: 42

env:
  domain_name: "cheetah"
  task_name: "run"

obs_config:
  position: [8]
  velocity: [9]

input_mapping:
  robot_states: ["velocity", "position"]

run_name: ${method_name}_${env.domain_name}_${env.task_name}_seed${seed}

training:
  selection_mode: "max_v"  # "max_v" or "max_q"
  use_wandb: true
  use_compile: true
  save_video: true
  save_video_every: 100000
  wandb_project_name: DMC


