# @package _global_
defaults:
  - /base_configs/maxVQ_dmc
  - /oracles/dmc/humanoid_run
  - _self_
method_name: "MaxVQ"

seed: 42

env:
  domain_name: "humanoid"
  task_name: "run"

obs_config:
  joint_angles: [21]
  head_height: [1]
  extremities: [12]
  torso_vertical: [3]
  com_velocity: [3]
  velocity: [27]

run_name: ${method_name}_${env.domain_name}_${env.task_name}_seed${seed}

training:
  selection_mode: "max_v"  # "max_v" or "max_q"
  use_wandb: true
  use_compile: true
  save_video: true
  save_video_every: 100000
  wandb_project_name: DMC


