# @package _global_
defaults:
  - /base_configs/cup_metaworld
  - /oracles/metaworld/pick-place
  - _self_
method_name: "CUP"

seed: 42

env:
  env_name: "pick-place-v3"
  camera_to_render: "corner4"
  seed: ${seed}

run_name: ${method_name}_${env.env_name}_seed${seed}

training:
  n_oracles: 2


