# @package _global_
defaults:
  - /base_configs/cup_dmc
  - /oracles/dmc/walker_run
  - _self_
method_name: "CUP"

seed: 42

env:
  domain_name: "walker"
  task_name: "run"

obs_config:
  orientations: [14]
  height: [1]
  velocity: [9]

run_name: ${method_name}_${env.domain_name}_${env.task_name}_seed${seed}

training:
  use_wandb: true
  save_video: true


