# @package _global_
defaults:
  - /base_configs/cup_box2d
  - /oracles/box2d/racingcar_learner
  - _self_

method_name: "CUP"
seed: 42

env:
  env_name: "racingcar"
  mode: "learner"
  stack_frames: 4
  max_steps: 2000
  seed: ${seed}

obs_config:
  state: [184]

run_name: ${method_name}_${env.env_name}_${env.mode}_seed${seed}

rl_agent_args:
  action_dim: 3
  action_high: [1.0, 1.0, 1.0]
  action_low: [-1.0, 0.0, 0.0]

rl_critic_args:
  action_dim: 3

oracle_actor_args:
  action_high: [1.0, 1.0, 1.0]
  action_low: [-1.0, 0.0, 0.0]



