# @package _global_
defaults:
  - /base_configs/qmix_metaworld
  - /oracles/metaworld/assembly
  - _self_
method_name: "QMP"

seed: 42

env:
  env_name: "assembly-v3"
  camera_to_render: "corner4"
  seed: ${seed}

run_name: ${method_name}_${env.env_name}_seed${seed}

training:
  n_oracles: 2


