# @package _global_
defaults:
  - /base_configs/bc_dmc
  - _self_

method_name: "BC_Acrobot_Sparse_DEBUG"
seed: 42

env:
  domain_name: "acrobot"
  task_name: "swingup_sparse"
  render_size: [128,128]
  n_sub_steps: 1
  seed: ${seed}
# Observation configuration (list shapes will be converted to tuples in code)
obs_config:
  orientations: [4]    # Joint angles
  velocity: [2]      # Head height


run_name: ${method_name}_${env.domain_name}_${env.task_name}_seed${seed}

training:
  # Offline dataset location (must contain *.npz episodes)
  replay_dir: "./checkpoints/Baseline_Cartpole_cartpole_swingup_sparse_seed0/replay_buffer"
  expert_dir: "./checkpoints/Baseline_Cartpole_cartpole_swingup_sparse_seed0"

  # Runtime knobs / logging
  use_compile: true
  use_wandb: true
  save_video_every: 100000
  save_video: true



