# @package _global_
defaults:
  - /base_configs/bc_dmc
  - _self_

method_name: "BC_Cartpole_Sparse_DEBUG"
seed: 42

env:
  domain_name: "cartpole"
  task_name: "swingup_sparse"
  render_size: [128,128]
  n_sub_steps: 1
  seed: ${seed}

obs_config:
  position: [3]
  velocity: [2]

run_name: ${method_name}_${env.domain_name}_${env.task_name}_seed${seed}

training:
  # Offline dataset location (must contain *.npz episodes)
  replay_dir: "./checkpoints/Baseline_Cartpole_cartpole_swingup_sparse_seed0/replay_buffer"
  expert_dir: "./checkpoints/Baseline_Cartpole_cartpole_swingup_sparse_seed0"

  # Runtime knobs / logging
  use_compile: true
  use_wandb: true
  save_video_every: 100000
  save_video: true



