# @package _global_
defaults:
  - /base_configs/bc_dmc
  - _self_

method_name: "BC_Cheetah_DEBUG"
seed: 42

env:
  domain_name: "cheetah"
  task_name: "run"

# Observation configuration (list shapes will be converted to tuples in code, if needed)
obs_config:
  position: [8]
  velocity: [9]

run_name: ${method_name}_${env.domain_name}_${env.task_name}_seed${seed}

training:
  # Offline dataset location (must contain *.npz episodes)
  replay_dir: "/share/data/ripl/jjt/projects/oracles/checkpoints/Baseline_Hopper_hopper_stand_seed0/replay_buffer"
  expert_dir: "/share/data/ripl/jjt/projects/oracles/checkpoints/Baseline_Hopper_hopper_stand_seed0"

  # Runtime knobs / logging
  use_compile: true
  use_wandb: true
  save_video_every: 100000
  save_video: true

