# @package _global_
defaults:
  - /base_configs/maxAdv_dmc
  - /oracles/dmc/cheetah_run
  - _self_
method_name: "DEBUG"


seed: 42

env:
  domain_name: "cheetah"
  task_name: "run"
  
# Observation configuration (list shapes will be converted to tuples in code)
obs_config:
  position: [8]
  velocity: [9]

# Input mapping for model inputs
input_mapping:
  robot_states: ["velocity", "position"]


run_name: ${method_name}_${env.domain_name}_${env.task_name}_seed${seed}
training:
  # Oracle configuration
  baseline_greedy_guided: true
  n_oracles: 3

  # Logging / runtime
  save_video_every: 100000
  use_wandb: true  # whether to use Weights & Biases for logging
  use_compile: true
  save_video: true  # Whether to save video
  wandb_project_name: DMC

  
  

