# @package _global_
defaults:
  - /base_configs/maxAdv_dmc
  - /oracles/dmc/hopper_hop
  - _self_
method_name: "DEBUG"


seed: 42

env:
  domain_name: "hopper"
  task_name: "hop"
  render_size: [128,128]
  n_sub_steps: 1
  seed: ${seed}

obs_config:
  position: [6]  # Joint orientations
  velocity: [7]         # Height of the walker
  touch: [2]      # Joint velocities

run_name: ${method_name}_${env.domain_name}_${env.task_name}_seed${seed}
training:
  # Oracle configuration
  baseline_greedy_guided: true
  n_oracles: 3
  # Logging / runtime
  save_video_every: 100000
  use_wandb: true  # whether to use Weights & Biases for logging
  use_compile: true
  save_video: true  # Whether to save video
  wandb_project_name: DMC

  
