# @package _global_
defaults:
  - /base_configs/simba_dmc
  - _self_
method_name: "Simba_DEBUG"
env:
  domain_name: "humanoid"
  task_name: "run"
  render_size: [128,128]
  n_sub_steps: 1
  seed: ${seed}
# Observation configuration (list shapes will be converted to tuples in code)
obs_config:
  joint_angles: [21]    # Joint angles
  head_height: [1]      # Head height
  extremities: [12]     # Extremity positions
  torso_vertical: [3]   # Torso vertical orientation
  com_velocity: [3]     # Center of mass velocity
  velocity: [27]        # Joint velocities

run_name: "${method_name}_${env.domain_name}_${env.task_name}_seed${seed}"

# Algorithm parameters
training:
  total_timesteps: 5000000
  capacity: 5000000
  exploration_decay_steps: 5000000
  max_exploration_std: 0.35
  min_exploration_std: 0.01
  save_video_every: 500000
  eval_every: 10000  # How often to evaluate the policy (steps)
  save_freq: 1000  # How often to save checkpoints (steps)
  resume: true  # Whether to resume from a checkpoint
  use_wandb: true  # whether to use Weights & Biases for logging
  track: true  # Whether to track metrics
  use_compile: true
  save_video: true  # Whether to save video