# @package _global_
defaults:
  - /base_configs/maxVQ_metaworld
  - /oracles/metaworld/hammer
  - _self_
method_name: "MaxVQ"

seed: 42

env:
  env_name: "hammer-v3"
  camera_to_render: "corner4"
  seed: ${seed}

run_name: ${method_name}_${env.env_name}_seed${seed}

training:
  n_oracles: 2


