# @package _global_
defaults:
  - /base_configs/maxAdv_metaworld
  - /oracles/metaworld/stick-pull
  - _self_
method_name: "CurrimaxAdv_StickPull_DEBUG"

seed: 42

env:
  env_name: "stick-pull-v3"
  camera_to_render: "corner4"
  seed: ${seed}

run_name: ${method_name}_${env.env_name}_seed${seed}

training:
  n_oracles: 2

