# @package _global_
defaults:
  - /paths
  - _self_
training:
  oracle_std_multiplier: [0.2, 0.2, 0.2]
oracles_dict:
  oracle_0: '${paths.project_root}/checkpoints/BC_Acrobot_Sparse_acrobot_swingup_sparse_seed0/BC_Acrobot_Sparse_acrobot_swingup_sparse_seed0_5999.pt'
  oracle_1: '${paths.project_root}/checkpoints/BC_Acrobot_Sparse_acrobot_swingup_sparse_seed0/BC_Acrobot_Sparse_acrobot_swingup_sparse_seed0_best.pt'
  oracle_2: '${paths.project_root}/checkpoints/BC_Acrobot_Sparse_acrobot_swingup_sparse_seed0/BC_Acrobot_Sparse_acrobot_swingup_sparse_seed0_19999.pt'

