# @package _global_
defaults:
  - /paths
  - _self_
training:
  oracle_std_multiplier: [0.2, 0.2, 0.6]
oracles_dict:
  oracle_0: '${paths.project_root}/checkpoints/BC_Cartpole_SWINGUP_SPARSE_cartpole_swingup_sparse_seed0/BC_Cartpole_SWINGUP_SPARSE_cartpole_swingup_sparse_seed0_1999.pt'
  oracle_1: '${paths.project_root}/checkpoints/BC_Cartpole_SWINGUP_SPARSE_cartpole_swingup_sparse_seed0/BC_Cartpole_SWINGUP_SPARSE_cartpole_swingup_sparse_seed0_999.pt'
  oracle_2: '${paths.project_root}/checkpoints/BC_Cartpole_SWINGUP_SPARSE_cartpole_swingup_sparse_seed0/BC_Cartpole_SWINGUP_SPARSE_cartpole_swingup_sparse_seed0_2999.pt'

