# @package _global_
training:
  oracle_std_multiplier: [0.2, 0.2, 0.2]
oracles_dict:
  oracle_0: '/share/data/ripl/jjt/projects/oracles/checkpoints/BC_Hopper_STAND_hopper_stand_seed0/BC_Hopper_STAND_hopper_stand_seed0_999.pt'
  oracle_1: '/share/data/ripl/jjt/projects/oracles/checkpoints/BC_Hopper_HOP_hopper_hop_seed0/BC_Hopper_HOP_hopper_hop_seed0_3999.pt'
  oracle_2: '/share/data/ripl/jjt/projects/oracles/checkpoints/BC_Hopper_HOP_hopper_hop_seed0/BC_Hopper_HOP_hopper_hop_seed0_5999.pt'

