# @package _global_
defaults:
  - /paths
  - _self_
training:
  oracle_std_multiplier: [0.2, 0.2, 0.2]
oracles_dict:
  oracle_0: '${paths.project_root}/checkpoints/BC_Humanoid_STAND_humanoid_stand_seed0/BC_Humanoid_STAND_humanoid_stand_seed0_9999.pt'
  oracle_1: '${paths.project_root}/checkpoints/BC_Humanoid_WALK_humanoid_walk_seed0/BC_Humanoid_WALK_humanoid_walk_seed0_9999.pt'
  oracle_2: '${paths.project_root}/checkpoints/BC_Humanoid_RUN_humanoid_run_seed0/BC_Humanoid_RUN_humanoid_run_seed0_19999.pt'

