# @package _global_
defaults:
  - /paths
  - _self_
training:
  oracle_std_multiplier: [0.2, 0.2, 0.2]
oracles_dict:
  oracle_0: null
  oracle_1: '${paths.project_root}/checkpoints/BC_Quad_WALK_quadruped_walk_seed0/BC_Quad_WALK_quadruped_walk_seed0_999.pt'
  oracle_2: '${paths.project_root}/checkpoints/BC_Quad_RUN_quadruped_run_seed0/BC_Quad_RUN_quadruped_run_seed0_999.pt'

