# @package _global_
defaults:
  - /paths
  - _self_
training:
  oracle_std_multiplier: [0.2, 0.2, 0.2]
oracles_dict:
  oracle_0: '${paths.project_root}/checkpoints/BC_Walker_STAND_walker_stand_seed0/BC_Walker_STAND_walker_stand_seed0_999.pt'
  oracle_1: '${paths.project_root}/checkpoints/BC_Walker_WALK_walker_walk_seed0/BC_Walker_WALK_walker_walk_seed0_1999.pt'
  oracle_2: '${paths.project_root}/checkpoints/BC_Walker_RUN_walker_run_seed0/BC_Walker_RUN_walker_run_seed0_1999.pt'

