# @package _global_
defaults:
  - /base_configs/maxAdv_dmc
  - _self_
method_name: "MaxAdv_Walker"


seed: 42

env:
  domain_name: "walker"
  task_name: "walk"
  render_size: [128,128]
  n_sub_steps: 1
  seed: ${seed}

obs_config:
  orientations: [14]  # Joint orientations
  height: [1]         # Height of the walker
  velocity: [9]      # Joint velocities


run_name: ${method_name}_${env.domain_name}_${env.task_name}_seed${seed}
training:
  # Oracle configuration
  baseline_greedy_guided: true
  n_oracles: 2
  oracle_std_multiplier: 0.5

  # Loss weights
  l1_loss_weight: 1.0
  rl_loss_weight: 1.0

  # Logging / runtime
  save_video_every: 100000
  use_wandb: true  # whether to use Weights & Biases for logging
  use_compile: true
  save_video: true  # Whether to save video
  wandb_project_name: DMC

oracles_dict:
  oracle_0: null
  oracle_1: '/share/data/ripl/jjt/projects/oracles/checkpoints/BC_Walker_walker_walk_seed42/BC_Walker_walker_walk_seed42_best.pt'
  
