# @package _global_
defaults:
  - /base_configs/maxAdv_dmc
  - _self_
method_name: "CurrMaxAdv_Quad"


seed: 42

env:
  domain_name: "quadruped"
  task_name: "run"
  render_size: [128,128]
  n_sub_steps: 1
  seed: ${seed}

# Observation configuration (list shapes will be converted to tuples in code)
obs_config:
  egocentric_state: [44]
  torso_velocity: [3]
  torso_upright: [1]
  imu: [6]
  force_torque: [24]

run_name: ${method_name}_${env.domain_name}_${env.task_name}_seed${seed}
training:
  # Oracle configuration
  baseline_greedy_guided: true
  n_oracles: 2
  oracle_std_multiplier: 0.5

  # Loss weights
  l1_loss_weight: 1.0
  rl_loss_weight: 1.0

  # Logging / runtime
  save_video_every: 100000
  use_wandb: true  # whether to use Weights & Biases for logging
  use_compile: true
  save_video: true  # Whether to save video
  wandb_project_name: DMC

  
oracles_dict:
  oracle_0: null
  oracle_1: '/share/data/ripl/jjt/projects/oracles/checkpoints/BC_Quad_quadruped_run_seed42/BC_Quad_quadruped_run_seed42_best.pt'
