# @package _global_
defaults:
  - /base_configs/maxAdv_dmc
  - _self_
method_name: "SharedMaxAdv_Cheetah_DEBUG"


seed: 42

env:
  domain_name: "cheetah"
  task_name: "run"
  
# Observation configuration (list shapes will be converted to tuples in code)
obs_config:
  position: [8]
  velocity: [9]

# Input mapping for model inputs
input_mapping:
  robot_states: ["velocity", "position"]


run_name: ${method_name}_${env.domain_name}_${env.task_name}_seed${seed}
training:
  # Oracle configuration
  baseline_greedy_guided: true
  n_oracles: 2
  oracle_std_multiplier: 0.25

  # Loss weights
  l1_loss_weight: 1.0
  rl_loss_weight: 1.0

  # Logging / runtime
  save_video_every: 100000
  use_wandb: true  # whether to use Weights & Biases for logging
  use_compile: true
  save_video: true  # Whether to save video
  wandb_project_name: DMC

  
oracles_dict:
  oracle_0: null
  oracle_1: '/share/data/ripl/jjt/projects/oracles/checkpoints/BC_Cheetah_DEBUG_cheetah_run_seed42/BC_Cheetah_DEBUG_cheetah_run_seed42_best.pt'
  

rl_agent_args:
  action_dim: 6
  action_high: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
  action_low: [-1.0, -1.0, -1.0, -1.0, -1.0, -1.0]
    

rl_critic_args:
  action_dim: 6

oracle_critic_args:
  action_dim: 6
  n_heads: 3

oracle_actor_args:
  noise_clip: 0.3
