# @package _global_
defaults:
  - /base_configs/bc_box2d
  - _self_

method_name: "BC_Bipedal_Jumper"

env:
  env_name: "bipedal"
  mode: "jumper"
  stack_frames: 4
  max_steps: 1500
  seed: ${seed}

obs_config:
  state: [136]

run_name: ${method_name}_${env.env_name}_${env.mode}_seed${seed}

training:
  replay_dir: ""
  expert_dir: ""

actor_args:
  action_high: [1.0, 1.0, 1.0, 1.0]
  action_low: [-1.0, -1.0, -1.0, -1.0]

