# @package _global_
training:
  oracle_std_multiplier: [0.2, 0.2, 0.2]
oracles_dict:
  oracle_0: '/share/data/ripl/jjt/projects/oracles/checkpoints/Simba_Bipedal_Climber_seed42/Simba_Bipedal_Climber_seed42_best.pt'
  oracle_1: '/share/data/ripl/jjt/projects/oracles/checkpoints/Simba_Bipedal_Jumper_seed42/Simba_Bipedal_Jumper_seed42_best.pt'
  oracle_2: '/share/data/ripl/jjt/projects/oracles/checkpoints/Simba_Bipedal_Skater_seed42/Simba_Bipedal_Skater_seed42_best.pt'

