# @package _global_
defaults:
  - /paths
  - _self_
training:
  oracle_std_multiplier: [0.2, 0.2, 0.2]
oracles_dict:
  oracle_0: '${paths.project_root}/checkpoints/Simba_Bipedal_Climber_seed42/Simba_Bipedal_Climber_seed42_best.pt'
  oracle_1: '${paths.project_root}/checkpoints/Simba_Bipedal_Jumper_seed42/Simba_Bipedal_Jumper_seed42_best.pt'
  oracle_2: '${paths.project_root}/checkpoints/Simba_Bipedal_Skater_seed42/Simba_Bipedal_Skater_seed42_best.pt'

