# @package _global_
defaults:
  - /paths
  - _self_
training:
  oracle_std_multiplier: [0.2, 0.2, 0.2]
oracles_dict:
  oracle_0: '${paths.project_root}/checkpoints/racingcar_bus/Simba_Racingcar_Bus/seed42/checkpoints/Simba_Racingcar_Bus_seed42_best.pt'
  oracle_1: '${paths.project_root}/checkpoints/racingcar_drifter/Simba_Racingcar_Drifter/seed42/checkpoints/Simba_Racingcar_Drifter_seed42_best.pt'
  oracle_2: '${paths.project_root}/checkpoints/racingcar_racer/Simba_Racingcar_Racer/seed42/checkpoints/Simba_Racingcar_Racer_seed42_best.pt'

