# @package _global_
training:
  oracle_std_multiplier: [0.2, 0.2, 0.2]
oracles_dict:
  oracle_0: '/share/data/ripl/jjt/projects/oracles/checkpoints/racingcar_bus/Simba_Racingcar_Bus/seed42/checkpoints/Simba_Racingcar_Bus_seed42_best.pt'
  oracle_1: '/share/data/ripl/jjt/projects/oracles/checkpoints/racingcar_drifter/Simba_Racingcar_Drifter/seed42/checkpoints/Simba_Racingcar_Drifter_seed42_best.pt'
  oracle_2: '/share/data/ripl/jjt/projects/oracles/checkpoints/racingcar_racer/Simba_Racingcar_Racer/seed42/checkpoints/Simba_Racingcar_Racer_seed42_best.pt'

