# @package _global_
defaults:
  - /paths
  - _self_
training:
  oracle_std_multiplier: [0.05, 0.05, 0.05]
oracles_dict:
  oracle_0: '${paths.project_root}/checkpoints/weather_Foggy/Simba_Weather_Foggy/seed42/checkpoints/Simba_Weather_Foggy_seed42_final.pt'
  oracle_1: '${paths.project_root}/checkpoints/weather_Rainy/Simba_Weather_Rainy/seed42/checkpoints/Simba_Weather_Rainy_seed42_best.pt'
  oracle_2: '${paths.project_root}/checkpoints/weather_Sunny/Simba_Weather_Sunny/seed42/checkpoints/Simba_Weather_Sunny_seed42_best.pt'

