# @package _global_
defaults:
  - /base_configs/loki_dmc
  - /oracles/dmc/hopper_hop
  - _self_
method_name: "LOKI"

seed: 42

env:
  domain_name: "hopper"
  task_name: "hop"

obs_config:
  position: [6]
  velocity: [7]
  touch: [2]

run_name: ${method_name}_${env.domain_name}_${env.task_name}_seed${seed}

training:
  n_oracles: 3
  use_wandb: true
  save_video: true



